=== AlbertoF17/Marcas/XML/Ejemplo1/personas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="sexo" type="xs:string" />
                            <xs:element name="fecha_nacimiento">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" type="xs:string" />
                                        <xs:element name="mes" type="xs:string" />
                                        <xs:element name="anyo" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ciudad" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="dni" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlbertoF17/Marcas/XML/Ejemplo1/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!-- COMENTARIO -->
<?xml-stylesheet type="text/css" href="estilos/estilos.css"?>
<personas dni="12345678A" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personas.xsd">
    <!-- CREA EL XSD AUTOMÁTICAMENTE -->
    <persona>
        <nombre>Elena</nombre>
        <sexo>Mujer</sexo>
        <fecha_nacimiento>
            <dia>12</dia>
            <mes>2</mes>
            <anyo>2001</anyo>
        </fecha_nacimiento>
        <ciudad>Madrid</ciudad>
    </persona>
    <persona>
        <nombre>Juan</nombre>
        <sexo>Hombre</sexo>
        <fecha_nacimiento>
            <dia>24</dia>
            <mes>2</mes>
            <anyo>2001</anyo>
        </fecha_nacimiento>
        <ciudad>Sevilla</ciudad>
    </persona>
    <persona>
        <nombre>Manuel</nombre>
        <sexo>Hombre</sexo>
        <fecha_nacimiento>
            <dia>8</dia>
            <mes>2</mes>
            <anyo>2009</anyo>
        </fecha_nacimiento>
        <ciudad>Sevilla</ciudad>
    </persona>
</personas>
